# Generated by Django 3.1 on 2020-09-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('IT', 'Information Technologies'), ('Bussiness Management', 'Bussiness Management'), ('Digital Marketing', 'Digital Marketing'), ('Computer Science', 'Computer Science'), ('Civil Engineering', 'Civil Engineering'), ('AI', 'Artificial Intelligence'), ('Other', 'Other')], default=1, max_length=120),
        ),
    ]
