from django.urls import path
from .views import (
    ProfileListView,
    ProfileCreateView,
    ProfileDetailView,
    ProfileUpdateView,
    ProfileDeleteView,
    EducationListView,
    EducationCreateView,
    EducationDetailView,
    EducationUpdateView,
    EducationDeleteView,
    ExperienceListView,
    ExperienceCreateView,
    ExperienceDetailView,
    ExperienceUpdateView,
    ExperienceDeleteView,
    SocialCreateView,
    SocialDetailView,
    SocialUpdateView,
    SocialDeleteView
)

app_name = 'profiles'
urlpatterns = [
    path(
        '',
        ProfileListView.as_view(),
        name='profiles_list'
    ),
    path(
        'create/',
        ProfileCreateView.as_view(),
        name='profiles_create'
    ),
    path(
        '<int:id>/detail/',
        ProfileDetailView.as_view(),
        name='profiles_detail'
    ),
    path(
        '<int:id>/delete/',
        ProfileDeleteView.as_view(),
        name='profiles_delete'
    ),
    path(
        '<int:id>/update/',
        ProfileUpdateView.as_view(),
        name='profiles_update'
    ),
    path(
        '<int:id>/educations/',
        EducationListView.as_view(),
        name='educations_list'
    ),
    path(
        '<int:id>/experiences/',
        ExperienceListView.as_view(),
        name='experiences_list'
    ),
    path(
        '<int:id>/educations/create',
        EducationCreateView.as_view(),
        name='educations_create'
    ),
    path(
        '<int:id>/experiences/create',
        ExperienceCreateView.as_view(),
        name='experiences_create'
    ),
    path(
        '<int:id>/socials',
        SocialDetailView.as_view(),
        name='socials_detail'
    ),
    path(
        '<int:id>/socials/create',
        SocialCreateView.as_view(),
        name='socials_create'
    ),
    path(
        '<int:id>/socials/update',
        SocialUpdateView.as_view(),
        name='socials_update'
    ),
    path(
        '<int:id>/socials/delete',
        SocialDeleteView.as_view(),
        name='socials_delete'
    ),
    path(
        '<int:profile_id>/educations/<int:education_id>/detail',
        EducationDetailView.as_view(),
        name='educations_detail'
    ),
    path(
        '<int:profile_id>/experiences/<int:experience_id>/detail',
        ExperienceDetailView.as_view(),
        name='experiences_detail'
    ),
    path(
        '<int:profile_id>/educations/<int:education_id>/update',
        EducationUpdateView.as_view(),
        name='educations_update'
    ),
    path(
        '<int:profile_id>/experiences/<int:experience_id>/update',
        ExperienceUpdateView.as_view(),
        name='experiences_update'
    ),
    path(
        '<int:profile_id>/educations/<int:education_id>/delete',
        EducationDeleteView.as_view(),
        name='educations_delete'
    ),
    path(
        '<int:profile_id>/experiences/<int:experience_id>/delete',
        ExperienceDeleteView.as_view(),
        name='experiences_delete'
    ),
]

